# PostgreSQL Secret for Development Namespace
# Deploy with: kubectl apply -f postgres-secret-dev.yaml
#
# This copies the postgres-secret to the development namespace so that
# generated apps can reference it. Cross-namespace secret access is not
# allowed in Kubernetes, so we need this copy.

apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: development
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/managed-by: chronosops
type: Opaque
stringData:
  password: chronosops-dev-password
