# PostgreSQL StatefulSet for ChronosOps Generated Apps
# Deploy with: kubectl apply -f postgres.yaml
#
# This provides a shared PostgreSQL instance for all generated apps
# that use storageMode: 'postgres' for scalable database persistence.
#
# Connection string format:
# postgres://postgres:$(POSTGRES_PASSWORD)@chronosops-postgres.database.svc.cluster.local:5432/<database-name>

---
# Database namespace for shared PostgreSQL instance
apiVersion: v1
kind: Namespace
metadata:
  name: database
  labels:
    app.kubernetes.io/managed-by: chronosops

---
# Secret for PostgreSQL password
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: database
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/managed-by: chronosops
type: Opaque
stringData:
  password: chronosops-dev-password

---
# StatefulSet for PostgreSQL
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: chronosops-postgres
  namespace: database
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/managed-by: chronosops
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
        app.kubernetes.io/name: postgres
        app.kubernetes.io/managed-by: chronosops
    spec:
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_USER
          value: postgres
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 1000m
            memory: 1Gi
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - postgres
          initialDelaySeconds: 15
          periodSeconds: 10
        volumeMounts:
        - name: postgres-data
          mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
      labels:
        app: postgres
        app.kubernetes.io/managed-by: chronosops
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 10Gi

---
# Service for PostgreSQL (internal cluster access)
apiVersion: v1
kind: Service
metadata:
  name: chronosops-postgres
  namespace: database
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/managed-by: chronosops
spec:
  type: ClusterIP
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres

---
# NodePort Service for PostgreSQL (external access from outside cluster)
# Use this when running ChronosOps API locally outside Kubernetes
# Access via: localhost:30432
apiVersion: v1
kind: Service
metadata:
  name: chronosops-postgres-external
  namespace: database
  labels:
    app: postgres
    app.kubernetes.io/name: postgres
    app.kubernetes.io/managed-by: chronosops
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
  - port: 5432
    targetPort: 5432
    nodePort: 30432
    protocol: TCP
    name: postgres
